apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "jai-test-react-template"
  description: "sample react app"
  annotations:
    github.com/project-slug: invincibleJai/jai-test-react-template
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/invinciblejai"
